# Matrix Methods in Data Analysis, Signal Processing, and Machine Learning

## MIT Open Course Ware 18.065

### Problem Set I.1 - Solutions using Python, numpy and Latex

#### 1) Give an example where a combination of three nonzero vectors in R4 is the zero vector. Then write your example in the form Ax = 0. What are the shapes of A and x and 0 ?

In [1]:
import numpy as np

In [2]:
x1 = np.array([1,1,1,1])
x2 = np.array([3,3,3,3])
# Vector that is the difference of the two above
x3 = np.array([2,2,2,2])

In [4]:
# Check
1*x1 + (-1)*x2 + 1*x3 

array([0, 0, 0, 0])

In [34]:
A = np.c_[x1,x2,x3]
A

array([[1, 3, 2],
       [1, 3, 2],
       [1, 3, 2],
       [1, 3, 2]])

In [35]:
x = np.vstack(np.array([1,-1,1]))
x

array([[ 1],
       [-1],
       [ 1]])

In [36]:
# Check Ax = 0 
np.matmul(A,x)

array([[0],
       [0],
       [0],
       [0]])

In [37]:
print('A shape: ',A.shape)
print('x shape: ',x.shape)
print('0 shape: ',np.matmul(A,x).shape)

A shape:  (4, 3)
x shape:  (3, 1)
0 shape:  (4, 1)


#### 4) Suppose A is the 3 by 3 matrix ones(3, 3) of all ones. Find two independent vectors x and y that solve Ax = 0 and Ay = 0. Write that first equation Ax = 0 (with numbers) as a combination of the columns of A. Why don’t I ask for a third independent vector with Az = 0 ?

In [39]:
A = np.ones((3,3))
A

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [42]:
x = np.vstack(np.array([1,-1,0]))
x

array([[ 1],
       [-1],
       [ 0]])

In [44]:
# Check result
np.matmul(A,x)

array([[0.],
       [0.],
       [0.]])

In [43]:
y = np.vstack(np.array([1,0,-1]))
y

array([[ 1],
       [ 0],
       [-1]])

In [46]:
# Check result
np.matmul(A,y)

array([[0.],
       [0.],
       [0.]])

In [66]:
# Write Ax = 0 as a linear combination of the columns of A
# Slice A columns
A0 = np.vstack(A[:,0])
A1 = np.vstack(A[:,1])
A2 = np.vstack(A[:,2])
# Linear combination
result = A0*x[0] + A1*x[1] + A2*x[2]
result

array([[0.],
       [0.],
       [0.]])

#### Why don’t I ask for a third independent vector with Az = 0 ?

A has dimension 1; 1 + 2 = 3, there is no third independent vector. That is, any vector satisfying Az = 0 can be written as a linear combination of x and y.

#### 9) Suppose the column space of an m by n matrix is all of R3. What can you say about m ? What can you say about n ? What can you say about the rank r ?

Column space of a matrix A is the space that includes all the vectors that can be written as a linear combination of the columns of A; that is, all vectors b such that Ax = b has a solution x. So, if the columns of an m x n matrix generate all of R3, they must be R3 columns; that is, m = 3. As for n, we know that it must be at least 3 (n >= 3): we need (at least) three independent vectors to generate a 3 dimensions. The rank r cannot be higher than 3 (because that's the value of m), but it cannot also be lower than that (otherwise we wouldn't be generating all of R3). Therefore, r = 3. 

#### 18) If A = CR, what are the CR factors of the matrix  \begin{bmatrix}   0 & A \\  0 & A \end{bmatrix}  ?  

The matrix factorizes as follows: $ \begin{bmatrix}   0 & A \\  0 & A \end{bmatrix} = \begin{bmatrix}   C \\  C \end{bmatrix}*\begin{bmatrix}   0 & R\end{bmatrix}$